sudo: false
dist: bionic
language: cpp

matrix:
  include:

    - os: linux
      env:
        - COMPILER=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libfreetype6-dev
            - libpng++-dev
            - zlib1g-dev
            - libunittest++-dev
            - libwxgtk3.0-dev
            - libportmidi-dev
            - libsqlite3-0
            - libsqlite3-dev
            - libfluidsynth-dev
            - fluid-soundfont-gm
            - libfontconfig1-dev
            - lsb-release

script:
  - export CC=$COMPILER
  - export CXX=${CC/gcc/g++}
  - export CXX=${CXX/clang/clang++}
  - $CXX --version
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DLENMUS_DOWNLOAD_BRAVURA_FONT:BOOL=OFF ..
  - make


